version: '3'


services:
  db:
    image: postgres:14.3
    container_name: ${DB_NAME}  
    restart: always
    ports:
      - "${DB_PORT}:5432" 
    environment:
      POSTGRES_DB: ${DB_NAME} 
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: 'America/El_Salvador'
      PGTZ: 'America/El_Salvador'
 